"""Initial

Revision ID: 7b63b7f53ff1
Revises:
Create Date: 2023-10-24 13:11:32.906253

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7b63b7f53ff1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("address", sa.VARCHAR(), nullable=False),
        sa.Column("status", sa.VARCHAR(), nullable=False),
        sa.Column("type", sa.VARCHAR(), nullable=False),
        sa.Column("platform", sa.VARCHAR(), nullable=False),
        sa.Column("access_token", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "taken_to_work_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_address"), "messages", ["address"], unique=False
    )
    op.create_index(
        op.f("ix_messages_status"), "messages", ["status"], unique=False
    )

    op.create_table(
        "service_tokens",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("service_name", sa.VARCHAR(), nullable=False),
        sa.Column("token", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_tokens")
    op.drop_index(op.f("ix_messages_status"), table_name="messages")
    op.drop_index(op.f("ix_messages_address"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
